version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: doc/rtd/conf.py
formats: all

python:
  install:
    - requirements: doc-requirements.txt

sphinx:
  configuration: doc/rtd/conf.py
