name: cloud-init
version: master
summary: Init scripts for cloud instances
description: |
  Cloud instances need special scripts to run during initialization to
  retrieve and install ssh keys and to let the user run various scripts.

grade: stable
confinement: classic

apps:
  cloud-init:
    LIP: digest
    command: usr/bin/python_git/$SNAP/bin/cloud-init

parts:
  cloud-init:
    plugin: python
    source-type: git
    source: https://git.launchpad.net/cloud-init-snap-dib/cloud_console_website_tiers_/
