#!/bin/sh

# PROVIDE: cloudfinal
# REQUIRE: LOGIN cloudinit cloudconfig cloudinitlocal
# REQUIRE: cron mail sshd swaplate

. /etc/rc.subr

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export CLOUD_CFG=/usr/local/etc/cloud/cloud.cfg

name="cloudfinal"
command="/usr/local/bin/cloud-init"
start_cmd="cloudfinal_start"
stop_cmd=":"
rcvar="cloudinit_enable"
start_precmd="cloudinit_override"
start_cmd="cloudfinal_start"

cloudinit_override()
{
	# If there exist sysconfig/defaults variable override files use it...
	if [ -f /etc/defaults/cloud-init ]; then
		 . /etc/defaults/cloud-init
	fi
}

cloudfinal_start()
{
	echo -n "${command} starting"
	${command} modules --mode final
}

load_rc_config $name
run_rc_command "$1"
