#!/bin/sh

# PROVIDE: cloudconfig
# REQUIRE: cloudinit
# BEFORE: sshd

$_rc_subr_loaded . /etc/rc.subr

name="cloudinit"
start_cmd="start_cloud_init"
start_cloud_init()
{
    /usr/pkg/bin/cloud-init modules --mode config
}

load_rc_config $name
run_rc_command "$1"
