.TH CLOUD-INIT-PER 1

.SH NAME
cloud-init-per \- Run a command with arguments at a specific frequency

.SH SYNOPSIS
.BR "cloud-init-per" " <frequency> <name> <cmd> [ arg1 [ arg2 [...]]]"

.SH DESCRIPTION
Run a command with arguments at a specific frequency.

This utility can make it easier to use boothooks or bootcmd on a per
"once" or "always" basis. For example:

    - [ cloud-init-per, once, mymkfs, mkfs, /dev/vdb ]

The cloud-init-per command replaced the cloud-init-run-module command.

.SH OPTIONS
.TP
.B "frequency"
This can be one of the following values:

.BR "once" ":"
run only once and do not re-run for new instance-id

.BR "instance" ":"
run only the first boot for a given instance-id

.BR "always" ":"
run every boot

.TP
.B "name"
A name to give the command to run to show up in logs.

.TP
.B "cmd [ arg1 [ arg2 [...]]]"
The actual command to run followed by any additional arguments.

.SH COPYRIGHT
Copyright (C) 2020 Canonical Ltd. License GPL-3 or Apache-2.0

.SH SEE ALSO
Full documentation at: <https://cloudinit.readthedocs.io>
