.TH CLOUD-ID 1

.SH NAME
cloud-id \- Report the canonical cloud-id for this instance

.SH SYNOPSIS
.BR "cloud-id" " [-h] [-j] [-l] [-i <INSTANCE_DATA>]"

.SH DESCRIPTION
cloud-id is the lowercase name of the cloud datasource discovered.

The cloud-id will be 'not run' when systemd generator has not run yet.
The cloud-id will be 'disabled' when cloud-init is disabled or when
ds-identify did not find a valid datasource.

See cloud-init status --long for more information.

.SH OPTIONS
.TP
.B "-h, --help"
Show help message and exit

.TP
.B "-j, --json"
Report all standardized cloud-id information as json

.TP
.B "-l, --long"
Report extended cloud-id information as tab-delimited string

.SH EXIT STATUS
.TP
0
On success
.TP
1
Due to an error
.TP
2
Due to cloud-init in a disabled state. See: cloud-init status --long
.TP
3
The cloud-init generator and discovery has not yet run.

.SH COPYRIGHT
Copyright (C) 2021 Canonical Ltd. License GPL-3 or Apache-2.0

.SH SEE ALSO
Full documentation at: <https://docs.cloud-init.io>
