#!/bin/sh
set -e

if [ "$1" = purge ]; then
   if [ -x "`which ucf 2>/dev/null`" ]; then
      ucf --purge /var/run/grub/menu.lst
   fi
   if [ -x "`which ucfr 2>/dev/null`" ]; then
      ucfr --purge grub /var/run/grub/menu.lst
   fi
fi

if [ "$1" = "remove" ]; then
   dpkg-divert --package grub-legacy-ec2 --remove --rename --divert \
      /usr/sbin/grub-set-default.real /usr/sbin/grub-set-default
fi
#DEBHELPER#
