#!/bin/sh

# PROVIDE: cloudfinal
# REQUIRE: LOGIN cloudinit cloudconfig cloudinitlocal
# REQUIRE: cron mail sshd swaplate

. /etc/rc.subr

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

name="cloudfinal"
command="/usr/local/bin/cloud-init"
start_cmd="cloudfinal_start"
stop_cmd=":"
rcvar="cloudinit_enable"
start_cmd="cloudfinal_start"

cloudfinal_start()
{
	echo -n "${command} starting"
	${command} modules --mode final
}

load_rc_config $name
run_rc_command "$1"
