#!/bin/sh

# PROVIDE: cloudinitlocal
# REQUIRE: ldconfig mountcritlocal 
# BEFORE:  NETWORKING cloudinit cloudconfig cloudfinal

. /etc/rc.subr

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

name="cloudinitlocal"
command="/usr/local/bin/cloud-init"
start_cmd="cloudlocal_start"
stop_cmd=":"
rcvar="cloudinit_enable"
start_cmd="cloudlocal_start"

cloudlocal_start()
{
	echo -n "${command} starting"
	${command} init --local
}

load_rc_config $name
run_rc_command "$1"
