#!/bin/sh

# PROVIDE: dsidentify
# REQUIRE: mountcritlocal
# BEFORE:  cloudinitlocal

. /etc/rc.subr

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

name="dsidentify"
command="/usr/local/lib/cloud-init/ds-identify"
start_cmd="dsidentify_start"
stop_cmd=":"
rcvar="cloudinit_enable"

dsidentify_start()
{
    echo "${command} starting"
    if kenv -q kernel_options | grep -q 'cloud-init=disabled'; then
        warn "cloud-init is disabled via kernel_options."
    elif test -e /etc/cloud/cloud-init.disabled; then
        warn "cloud-init is disabled via cloud-init.disabled file."
    else
        ${command}
    fi
}

load_rc_config 'cloudinit'

: ${cloudinit_enable="NO"}

run_rc_command "$1"
