#!/bin/sh
CI_SOCKET="/run/cloud-init/unix.socket"
STAGE=`basename ${0}`
COMMAND=${STAGE#cloud-init-*}
for x in 1 2 3 4 5 6 7 8 9; do
    if [ -e "${CI_SOCKET}" ]; then
        break;
    fi
    sleep 0.3
done
echo "{\"command\": \"$COMMAND\"}" | nc -U ${CI_SOCKET}
