#!/bin/sh
# This file is part of cloud-init. See LICENSE file for license information.

# This script writes DHCP lease information into the cloud-init run directory
# It is sourced, not executed.  For more information see dhclient-script(8).

is_azure() {
    local dmi_path="/sys/class/dmi/id/board_vendor" vendor=""
    if [ -e "$dmi_path" ] && read vendor < "$dmi_path"; then
        [ "$vendor" = "Microsoft Corporation" ] && return 0
    fi
    return 1
}

is_enabled() {
    # only execute hooks if cloud-init is enabled and on azure
    [ -e /run/cloud-init/enabled ] || return 1
    is_azure
}

if is_enabled; then
   case "$reason" in
      BOUND) cloud-init dhclient-hook up "$interface";;
      DOWN|RELEASE|REBOOT|STOP|EXPIRE)
         cloud-init dhclient-hook down "$interface";;
   esac
fi
