#!/bin/sh

Usage() {
   cat <<EOF
Usage: ${0##*/} version
   make a tarball of 'version'
   must be in a bzr directory, and 'version' must be a tag

EOF
}

topdir=$PWD
tag=${1}

[ -n "$tag" ] || { Usage 1>&2 ; exit 1; }

tmpd=$(mktemp -d ); 
trap "rm -Rf '${tmpd}'" 0

out=${topdir}/cloud-init_${tag}.orig.tar.gz

cd ${tmpd} && 
   bzr branch -r "tag:${tag}" "${topdir}" ./cloud-init-${tag} &&
   tar czf "${out}" cloud-init-${tag}/ --exclude cloud-init-${tag}/.bzr &&
   echo "wrote ${out}"
