#!/bin/sh
#
#    92-ec2-upgrade-available - update-motd script
#
#    Copyright (C) 2010 Canonical Ltd.
#
#    Authors: Scott Moser <smoser@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Determining if updates are available is possibly slow.
# a cronjob runs occasioinally and updates a file with information
# on the latest available release (if newer than current)

BUILD_FILE=/var/lib/cloud/data/available.build

[ -s "${BUILD_FILE}" ] || exit 0

read suite build_name name serial other < "${BUILD_FILE}"

cat <<EOF
A newer build of the Ubuntu ${suite} ${build_name} image is available.
It is named '${name}' and has build serial '${serial}'.
EOF
