#!/usr/bin/env python3

import os
import sys


def main():
    if "avoid-pep8-E402-import-not-top-of-file":
        _tdir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        sys.path.insert(0, _tdir)
        from cloudinit import templater

        templater.render_cloudcfg(sys.argv[1:])


if __name__ == "__main__":
    main()
