#!/bin/bash

CR="
"
pycheck_dirs=( "cloudinit/" "tests/" "tools/" )

set -f
if [ $# -eq 0 ]; then
   files=( "${pycheck_dirs[@]}" )
else
   files=( "$@" )
fi

cmd=( "python3" -m "pyflakes" "${files[@]}" )

echo "Running: " "${cmd[@]}" 1>&2
exec "${cmd[@]}"
