#!/bin/bash

if [ $# -eq 0 ]; then
   files=( $(find * -name "*.py" -type f) )
else
   files=( "$@" );
fi 

cmd=(
    pylint
    --reports=n
    --include-ids=y
    --max-line-length=79

    --disable=R
    --disable=I

    --disable=W0142 # Used * or ** magic
    --disable=W0511 # TODO/FIXME note
    --disable=W0702 # No exception type(s) specified
    --disable=W0703 # Catch "Exception"

    --disable=C0103 # Invalid name
    --disable=C0111 # Missing docstring

    "${files[@]}"
)

echo -e "\nRunning pylint:"
echo "${cmd[@]}"
"${cmd[@]}"

