name: "Daily 25.10: lxd_container"

on:
  workflow_dispatch:
    inputs:
      install_source:
        required: false
        type: string
        default: 'ppa:cloud-init-dev/daily'
      image_type:
        required: true
        type: choice
        options:
        - generic
        - minimal
      filter_tests:
        required: false
        type: string
  schedule:
    - cron: '2 22 * * *'

jobs:
  questing-lxd_container:
    uses: ./.github/workflows/100-dispatch-common.yml
    with:
      release: questing
      platform: lxd_container
      install_source: ${{ inputs.install_source || 'ppa:cloud-init-dev/daily' }}
      image_type: ${{ inputs.image_type || 'generic' }}
      filter_tests: ${{ inputs.filter_tests }}
    secrets:
      PYCLOUDLIB_TOML_B64: ${{ secrets.PYCLOUDLIB_TOML_B64 }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
