name: "Daily 26.04: lxd_container"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 22 * * *'

jobs:
  resolute-lxd_container:
    uses: ./.github/workflows/100-dispatch-common.yml
    with:
      release: resolute
      platform: lxd_container
    secrets:
      PYCLOUDLIB_TOML: ${{ secrets.PYCLOUDLIB_TOML }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
