name: "Daily 24.04: lxd_vm"

on:
  workflow_dispatch:
    inputs:
      install_source:
        required: false
        type: string
        default: 'ppa:cloud-init-dev/daily'
  schedule:
    - cron: '2 23 * * *'

jobs:
  noble-lxd_vm:
    uses: ./.github/workflows/100-dispatch-common.yml
    with:
      release: noble
      platform: lxd_vm
      install_source: ${{ inputs.install_source || 'ppa:cloud-init-dev/daily' }}
      image_type: generic
    secrets:
      PYCLOUDLIB_TOML_B64: ${{ secrets.PYCLOUDLIB_TOML_B64 }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
