name: "Twice weekly 24.04: ec2"

on:
  workflow_dispatch:
    inputs:
      install_source:
        required: false
        type: string
        default: 'ppa:cloud-init-dev/daily'
  schedule:
    # Run Mon & Thurs for high-cost test runs
    - cron: '2 22 * * 1,4'

jobs:
  noble-ec2:
    uses: ./.github/workflows/100-dispatch-common.yml
    with:
      release: noble
      platform: ec2
      install_source: ${{ inputs.install_source || 'ppa:cloud-init-dev/daily' }}
      image_type: generic
    secrets:
      PYCLOUDLIB_TOML_B64: ${{ secrets.PYCLOUDLIB_TOML_B64 }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
