name: "Twice weekly 24.04: oci"

on:
  workflow_dispatch:
    inputs:
      install_source:
        required: false
        type: string
        default: 'ppa:cloud-init-dev/daily'
      image_type:
        required: true
        type: choice
        options:
        - generic
        - minimal
      filter_tests:
        required: false
        type: string
  schedule:
    # Run Mon & Thurs to reduce additional cost on shared external tokens
    - cron: '2 22 * * 1,4'

jobs:
  noble-oci:
    runs-on: ubuntu-latest
    if: github.repository == 'canonical/cloud-init'
    env:
      REQUIRED_SECRET: ${{ secrets.PYCLOUDLIB_TOML_B64 }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PYCLOUDLIB_OCI_CONFIG_B64: ${{ secrets.PYCLOUDLIB_OCI_CONFIG_B64 }}
      PYCLOUDLIB_OCI_KEY_B64: ${{ secrets.PYCLOUDLIB_OCI_KEY_B64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Assert OCI repo secrets are set
        shell: bash
        run: |
          if [ -z "$PYCLOUDLIB_OCI_CONFIG_B64" ]; then
             echo "ERROR: Missing required repo secret. Please provide PYCLOUDLIB_OCI_CONFIG_B64 repo secret at ${{ github.repository }}/settings/secrets/actions."
             exit 1
          fi
          if [ -z "$PYCLOUDLIB_OCI_KEY_B64" ]; then
             echo "ERROR: Missing required repo secret. Please provide PYCLOUDLIB_OCI_KEY_B64 repo secret at ${{ github.repository }}/settings/secrets/actions."
             exit 1
          fi
      - name: Setup OCI credentials
        shell: bash
        env:
          PYCLOUDLIB_OCI_CONFIG_FILE_PATH: ${{ runner.temp }}/oci/config
          PYCLOUDLIB_OCI_KEY_FILE_PATH: ${{ runner.temp }}/oci/key.pem
        run: |
          mkdir -p "$(dirname "$PYCLOUDLIB_OCI_CONFIG_FILE_PATH")"
          sh -c 'printf "%s\n" "$PYCLOUDLIB_OCI_CONFIG_B64" | base64 -d > "$PYCLOUDLIB_OCI_CONFIG_FILE_PATH"'
          sh -c 'printf "%s\n" "$PYCLOUDLIB_OCI_KEY_B64" | base64 -d  | install -m 600 /dev/stdin "$PYCLOUDLIB_OCI_KEY_FILE_PATH"'
      - name: Run integration tests
        uses: ./.github/actions/integration-test
        with:
          release: noble
          platform: oci
          install_source: ${{ inputs.install_source || 'ppa:cloud-init-dev/daily' }}
          image_type: ${{ inputs.image_type || 'generic' }}
          filter_tests: ${{ inputs.filter_tests }}
