name: scheduled-linkcheck
on:
  schedule:
    - cron: '3 14 * * *'
concurrency:
  group: 'ci-${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  linkcheck:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.failOnError == 'true') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0

      - name: "Install Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Install tox
        run: pip install tox

      - name: Run Sphinx linkcheck
        run: tox -e linkcheck | tee output.txt

      - name: Check for broken links below threshold
        run: |
          broken_count=$(grep -c "broken" output.txt)
          if [[ $broken_count -ge 5 ]]; then
            echo "Too many broken links detected: $broken_count"
            broken_matches=$(grep "broken" output.txt)
            echo "Broken links \n$broken_matches"
            exit 1
          else
            echo "Number of broken links is below threshold: $broken_count"
          fi
