name: Packaging

on:
  pull_request:
    branches:
      - 'ubuntu/**'

concurrency:
  group: 'ci-${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

defaults:
  run:
    shell: sh -ex {0}

env:
  RELEASE: focal

jobs:
  check-patches:
    name: Check patches
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all branches for merging
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prepare dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install tox quilt
      - name: Setup quilt environment
        run: |
          echo 'QUILT_PATCHES=debian/patches' >> ~/.quiltrc
          echo 'QUILT_SERIES=debian/patches/series' >> ~/.quiltrc

      - name: Configure git and merge
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge origin/main
      - name: Quilt patches apply successfully and tests run
        run: |
          if [ ! -f debian/patches/series ]; then
            echo "no patches, skipping"
            exit 0
          fi
          quilt push -a
          tox -e py3
          quilt pop -a
